### ISSUE TITLE
[BUG?] SourcemodStore is crashing after having installed that

### ISSUE THREAD

**Issue by Linguistie** [SaengerItsWar/shavit-credits#5]
Crashed my sourcemod store plugin after installing this

```
L 12/07/2020 - 12:28:53: [SM] Unable to load plugin "shavit-credits.smx": Could not find required plugin "store-core"
CGameEventManager::AddListener: event 'player_connect_client' unknown.
CGameEventManager::AddListener: event 'game_round_end' unknown.
CGameEventManager::AddListener: event 'teamplay_win_panel' unknown.
CGameEventManager::AddListener: event 'arena_win_panel' unknown.
CGameEventManager::AddListener: event 'round_win' unknown.
CGameEventManager::AddListener: event 'game_round_restart' unknown.
CGameEventManager::AddListener: event 'game_round_end' unknown.
CGameEventManager::AddListener: event 'teamplay_win_panel' unknown.
CGameEventManager::AddListener: event 'arena_win_panel' unknown.
CGameEventManager::AddListener: event 'teamplay_restart_round' unknown.
CGameEventManager::AddListener: event 'round_win' unknown.
CGameEventManager::AddListener: event 'dod_game_over' unknown.
CGameEventManager::AddListener: event 'teamplay_game_over' unknown.
CGameEventManager::AddListener: event 'tf_game_over' unknown.
```

**Comment by SaengerItsWar** [comment]
Which store plugin do you have installed?

**Comment by Linguistie** [comment]
https://github.com/SourceMod-Store/Sourcemod-Store

**Comment by SaengerItsWar** [comment]
Ok I will look later cause a Update for the timer is out so the include has to be updated and also recompile the plugin.

**Comment by Linguistie** [comment]
I m pretty new to this, so this might be an issue on my part, but the store loaded with !shop after installing the store itself, but after the shavit-credits installation I started getting this in the server chat when writing !shop:
`[Store] No categories are currently available.`
I checked the console and saw the error posted above.

but thanks for the response, I'll be waiting for the update

**Comment by SaengerItsWar** [comment]
Yeah i think it might be a bug and thanks for reporting

**Comment by SaengerItsWar** [comment]
I've updated the plugin includes and fixed a little bug and uploaded the latest compiled version
just download and test it please.
[https://github.com/SaengerItsWar/shavit-credits/raw/store/plugins/shavit-credits.smx](https://github.com/SaengerItsWar/shavit-credits/raw/store/plugins/shavit-credits.smx)

**Comment by Linguistie** [comment]
Regarding my first message, I could not access !shop previously because I should have written !store instead of !shop. I had (and still have) no items in the shop, so I was getting
`[Store] No categories are currently available.`
I can access the !store with and without this plugin, so it is working fine.

That being said, I'm still getting the message bellow even after redownloading .zip from your git rep and the new .smx (and the plugin still isn't working):
`L 12/07/2020 - 21:39:53: [SM] Unable to load plugin "shavit-credits.smx": Could not find required plugin "store-core"`.

I'm new to making servers, so all of this might be because I didn't install something properly.
This is my store related sm_plugins_list:
`  42 <Failed> "[shavit] Credits | Sourcemod Store" (1.4.3) by SaengerItsWar`
 ```
 64 "[Store] Backend Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  65 "[Store] Core Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  66 "[Store] Distributor Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  67 "[Store] Gifting Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  68 "[Store] Inventory Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  69 "[Store] Loadouts Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  70 "[Store] Logging Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  71 "[Store] Refunds Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
  72 "[Store] Shop Module" (1.2 Final) by Alongub, Keith Warren(Drixevel), Arrow768
```

My installation process: 

Sourcemod-Store-1.2-Final:
1. downloaded the zip file from github
2. extracted translations, scripting, plugins, configs into addons/sourcemod
3. connected it with my MySQL db via databases.cfg
4. checked the db itself to see if it connected properly
(no items have been added yet)

shavit-credits:
1. downloaded the zip file from github
2. extracted translations, scripting, plugins into addons/sourcemod
3. downloaded the .smx above and put it into addons/plugins
4. started the server

Where is it trying to look for the [store-core]? If these are the locations below, then I have them there.
scripting/include/store/store-core.inc? 
/plugins/store-core.smx?
/scripting/store-core.sp?

**Comment by SaengerItsWar** [comment]
It searches after the plugins/store-core.smx.

Try to recompile the hole store plugin the version you use is a older one that was compiled with an older sourcemod version maybe this is the problem.

To compile
1. Download the latest sourcemod version
2. Extract it into a new folder
3. Download the store
4. Extract the store into plugins/ scripting/includes/store/ ...
5. Start the compile.exe it will compile everything for you
6. When it's done without an error then the compiled plugin is under scripting/compiled/
7. Just put the compiled version on your server.

**Comment by Linguistie** [comment]
I'll write my installation process just in case

1. downloaded Sourcemod 6501 stable build from 1.10 branch https://www.sourcemod.net/downloads.php?branch=stable
2. made a new folder on _C:\Sourcemod_testing_folder_
3. extracted the contents of the sourcemod-1.10.zip into _C:\Sourcemod_testing_folder_
4. downloaded SourcemodStore .zip by pressing Code -> Download ZIP from the master https://github.com/SourceMod-Store/Sourcemod-Store
5. extracted the contents (except for README, LICENSE, .gitignore and .gitattributes) of the Sourcemod-Store-master.zip into sourcemod_testing_folder/addons 
6. executed compile.exe in _C:\Sourcemod_testing_folder\addons\sourcemod\scripting_
7. dragged and dropped the newly-compiled .smx from _C:\Sourcemod_testing_folder\...\compiled_ into _\plugins_ of my server and agreed to replace the old files
8. launched the server

So, it didn't work now, I assume it is because it was compiled under a different path and not from the server directory so it is trying to find things in the old source_testing_folder directory? Or should I have made a new folder in the same folder as my server?
```
Errors:
shavit-credits.smx ([shavit] Credits | Sourcemod Store): Could not find required plugin "store-core"
store-backend.smx ([Store] Backend Module): Could not find required plugin "store"
store-core.smx ([Store] Core Module): unexpected error 23 in AskPluginLoad callback
store-distributor.smx ([Store] Distributor Module): Could not find required plugin "store-core"
store-gifting.smx ([Store] Gifting Module): Could not find required plugin "store-core"
store-inventory.smx ([Store] Inventory Module): Could not find required plugin "store-core"
store-loadouts.smx ([Store] Loadouts Module): Could not find required plugin "store-core"
store-logging.smx ([Store] Logging Module): Could not find required plugin "store-core"
store-refunds.smx ([Store] Refunds Module): Could not find required plugin "store-core"
store-shop.smx ([Store] Shop Module): Could not find required plugin "store-core"
store-trading.smx ([Store] Trading Module):
```

Maybe I should try updating the sourcemod in my server? Idk if that would break it the whole server tho (again, first time doing all of that so maybe that's a regular practice)

**Comment by SaengerItsWar** [comment]
Ok i have to look later about that when I'm back home when i have a test system

**Comment by Linguistie** [comment]
Ok, so I have updated sourcemod, reinstalled the store, deleted some obsolete/older versions of the sourcemod store plugins (+the not working store-trading.smx) and the shavit-credits.smx seems to be showing up in the _sm plugins list_ now

Trying to figure out if it is working as intended now

UPDATE: Actually, nevermind, I can't even do !store now.

UPDATE2: Guess they did show up, but because all of them were on the same level in _sm plugins list_ I thought they all loaded in. Guess they were on the same line because all of them failed:
```
  83 <Error> "[shavit] Credits | Sourcemod Store" (1.4.3) by SaengerItsWar
  84 <Error> "[Store] Core Module" (1.3.0 dev1) by Alongub, Keith Warren(Drixevel), Arrow768
  85 <Failed> "[Store] Distributor Module" (1.3.0 dev1) by Alongub, Keith Warren(Drixevel), Arrow768
  86 <Failed> "[Store] Gifting Module" (1.3.0 dev1) by Alongub, Keith Warren(Drixevel), Arrow768
  87 <Failed> "[Store] Inventory Module" (1.3.0 dev1) by Alongub, Keith Warren(Drixevel), Arrow768
  88 <Failed> "[Store] Loadouts Module" (1.3.0 dev1) by Alongub, Keith Warren(Drixevel), Arrow768
  89 <Failed> "[Store] Logging Module" (1.3.0 dev1) by Alongub, Keith Warren(Drixevel), Arrow768
  90 <Failed> "[Store] Refunds Module" (1.3.0 dev1) by Alongub, Keith Warren(Drixevel), Arrow768
  91 <Failed> "[Store] Shop Module" (1.3.0 dev1) by Alongub, Keith Warren(Drixevel), Arrow768
  92 <Failed> "[UMC] Map Rate Reweight" (3.7.1) by Previous:Steell,Powerlord - Current: Mr.Silence
```
I'll update this thread once I figure out why this is happening

UPDATE3: Well, looks like I m stuck, I can't really test the plugin because it seems like I can't get store plugin to work anymore, so I guess untill I figure why it started asking for a new entry that I have no idea how to make I'll be trying to figure it out. 
`Exception reported: No config entry found for 'store_ext' in databases.cfg.`

UPDATE4: My current assumption is that the store plugin development has been terminated and instead of downloading it from github I previously downloaded it from this post https://forums.alliedmods.net/showpost.php?p=2484935&postcount=404 which made the store plugin work, but due to having an old version of the plugin - shavit-credits didn't work. So I m considering setting up a different shop now, if this is true. (Or probably I just installed something wrong as always)

UPDATE5: installed Zephyrus/dvarnai store version of this plugin and it seems to be working fine so far.
